image: cpaulik/gitlab-ci-image:v2

before_script:
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda env create -f conda_environment.yml
  - source activate smecv_grid
  - conda list

after_script:
  - conda env remove -n smecv_grid

variables:
  GIT_SSL_NO_VERIFY: "true"
  PIP_EXTRA_INDEX_URL: "http://dvlp1.geo.tuwien.ac.at:8080/simple"
  PIP_TRUSTED_HOST: "dvlp1.geo.tuwien.ac.at"
  NO_PROXY: "dvlp1.geo.tuwien.ac.at,$NO_PROXY"
  no_proxy: "dvlp1.geo.tuwien.ac.at,$no_proxy"

stages:
- test

test_job:
  stage: test
  script:
    - python setup.py test
